client_api_url:
code_repo:
description: Metric flow is a multi-account reporting solution that aggregates metrics from multiple platforms, aggregates and correlates them to business goals.
docs_repo:
module_name: MetricFlow
name: Metric FLow
project_id: 5217fb4a-e2cd-493d-9e5f-2482fb8c4f2c
current_user_email: "johns10@gmail.com"
account_id: 1cf53ab2-14ea-4e5f-9560-f16c1ed310fa
ignored_components:
  - MetricFlow.Repo
  - MetricFlowWeb.Endpoint
  - MetricFlowWeb.Router
  - MetricFlow.Mailer
  - MetricFlowWeb.Telemetry
  - MetricFlow.Application
  - MetricFlowWeb.Gettext
